<!--搜索条件头部-->
<div class="mbot30">
    {% set search_action = page_search["link"] %}
    <form action='{{ url(search_action) }}' autocomplete="on">
        <div class="form-group">
            <div class="form-inline">
                {% set conditions = page_search["conditions"] | default([]) %}
                {% for element in conditions %}
                {% if element["type"] == 0 %}
                <div class="form-group">
                    {% set search_keys = element["keys"] %}
                    {% set search_key_default = element["key_default"] %}
                    {% set search_value_default = element["value_default"] %}
                    {% set empty_text = element["empty_text"] | default("全部") %}
                    {% set empty_value = element["empty_value"] | default("") %}
                    {{ select("search_key", search_keys, 'useEmpty': true, 'emptyText': empty_text, 'emptyValue': empty_value, "class":"form-control", "value": search_key_default) }}
                    {{ text_field("search_value", "class":"form-control", "value":search_value_default) }}
                </div>
                {% elseif element["type"] == 1 %}
                <div class="form-group">
                    <label class="control-label">{{ element["label"] }}</label>
                    {% set empty_text = element["empty_text"] | default("全部") %}
                    {% set empty_value = element["empty_value"] | default("") %}
                    {{ select(element["key"], element["options"], 'useEmpty': true, 'emptyText': empty_text, 'emptyValue': empty_value, "class":"form-control", "value": element['value'] | default("")) }}
                </div>
                {% elseif element["type"] == 2 %}
                {% set date_type = element["date_type"] | default(0) %}
                {% if date_type == 0 %}
                <div class="form-group">
                    <label class="control-label">{{ element["label"] }}</label>
                    <div class="form-group">
                        <div class="input-group date">
                            {% set date = element["date"] | default([]) %}
                            {% set key = date["key"] | default("mg_date") %}
                            {% set value = date["value"] | default("") %}
                            {{ text_field(key, "class":"form-control  cond-date", "value": value) }}
                            <span class="input-group-addon"><i class="fa fa-th"></i></span>
                        </div>
                    </div>
                </div>
                {% elseif date_type == 1 %}
                <div class="form-group">
                    <label class="control-label">{{ element["label"] }}</label>
                    <div class="form-group">
                        <div class="input-group input-daterange">
                            {% set date_start = element["date_start"] | default([]) %}
                            {% set key_start = date_start["key"] | default("mg_date_start") %}
                            {% set value_start = date_start["value"] | default("") %}
                            {{ text_field(key_start, "class":"form-control cond-date", "value": value_start) }}
                            <span class="input-group-addon">to</span>
                            {% set date_end = element["date_end"] | default([]) %}
                            {% set key_end = date_end["key"] | default("mg_date_end") %}
                            {% set value_end = date_end["value"] | default("") %}
                            {{ text_field(key_end, "class":"form-control cond-date", "value": value_end) }}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% elseif element["type"] == 3 %}
                {{ hidden_field(element["key"], "value": element['value']) }}

                {% elseif element["type"] == 4 %}
                <div class="form-group">
                    <label class="control-label">{{ element["label"] }}</label>
                    {{ text_field(element["key"], "class":"form-control cond-date", "value":  element['value']) }}
                </div>
                {% endif %}
                &nbsp;
                {% if (element["br"] | default(false)) %}
                <br>
                {% endif %}
                {% endfor %}
                <div class="form-group">
                    {{ submit_button('筛选', 'class': 'btn btn-success') }}
                </div>
                <div class="form-group">
                    {{ partial("partials/tp_page_header") }}
                </div>
            </div>
        </div>
    </form>
</div>
<!--数据列表-->
<!--角色列表内容-->
{% set tb_trs = page_table["trs"] | default([]) %}
{% set tb_ths = page_table["ths"] | default([]) %}
<div>
    <table class="table table-bordered table-hover table-invoice">
        <thead>
        <tr>
            {# 表格标题区起始 #}
            {% for item in tb_ths %}
            <th width="{{ item['width'] | default('') }}" class="{{ item['class'] | default('') }}" >{{ item['name'] }}</th>
            {% endfor %}
            {# 表格标题区结束 #}
        </tr>
        </thead>

        <tbody>
        {# 表格数据区起始 #}
        {# tb_trs_data表示全部列表数据 #}
        {% set tb_trs_start = tb_trs['start'] | default(1) %}
        {% set tb_trs_data = tb_trs['data'] | default(null) %}
        {% for index in 0..tb_trs_data | length %}
        {# 判断数据是否有效 #}
        {% if tb_trs_data[index] is defined %}
        {# item表示一条列表数据中数据 #}
        {% set item = tb_trs_data[index] %}
        {% set id = item['id'] %}
        <tr>
            {# 数据区起始 #}
            {# 编号 #}
            {# 其他字段 #}
            {% if tb_trs['using'] is defined %}
            {# 仅使用using中指定字段 #}
            {% set fields = tb_trs['using'] %}
            {% for field in fields %}
            <td align="{{ field['align'] | default('') }}">
                {% set filed_type = field['type'] | default("text") %}
                {% if (filed_type == "image") %}
                <image class="img-thumbnail" src="{{ item[field['field']] }}" alt="图片">
                    {% else  %}
                    {{ item[field['field']] }}
                    {% endif %}
            </td>
            {% endfor %}
            {% else %}
            {# 使用全部字段 #}
            {% for item_filed in item %}
            <td>{{ item_filed }}</td>
            {% endfor %}
            {% endif %}
            {# 数据区结束 #}

            {# 操作区起始 #}
            {# ops表示所有操作 #}
            {% set ops = tb_trs['op'] | default(null) %}
            {% if ops is defined %}
            <td align="center">
                <!--{% set actions = op['actions'] | default([]) %}-->
                {% set indexs = 0 %}
                {% for action in ops %}
                {# 属性id前缀，默认前缀 MG #}
                {% set id_pre = action['id_pre'] | default("MG") %}

                {# 当产品是上架时 隐藏删除修改#}

                {% if item['vstate']!= 1 and  (id_pre == 'fh_') %}
                {% continue %}
                {% endif %}

                {% if item['vstate']!= 2 and  (id_pre == 'wl_') %}
                {% continue %}
                {% endif %}

                {% if item['vstates']!= 4 and  (id_pre == 'tk_') %}
                {% continue %}
                {% endif %}

                {% set url = action['link'] %}
                {% set action_tip = action['tip'] | default(false) %}
                {% set target = action['target'] | default("_self") %}
                {# 默认参数 #}
                {% set query_id = ['id':id] %}
                {% set query_params = null %}
                {# 操作类型 #}
                {% if action['multiple'] is defined and action['key'] is defined %}
                {# 带有状态的操作，比如(启用/禁用) #}
                {# 获取状态值 #}

                {% set am_index = item[action['key']] %}
                {# action_attr当前状态下全部属性 #}
                {% set action_attr = action['multiple'][am_index] %}
                {# 属性class #}
                {% set action_class = action_attr['class'] | default(null) %}
                {# 操作名称 #}
                {% set action_name = action_attr['name'] | default("") %}
                {% set query_params = action['key'] ~ "=" ~ am_index %}
                {% else %}
                {# 属性class #}
                {% set action_class = action['class'] | default(null) %}
                {# 操作名称 #}
                {% set action_name = action['name'] | default("") %}
                {% endif %}

                {# a 标签使用post方式提交请求, 务必引用qst_table.js #}
                {% if (action['method'] | default("get")) == "post" %}
                {% set action_class = action_class ~ " mg_post" %}
                {% endif %}
                {% if query_params is defined %}
                {% set url = url ~ "?" ~ query_params %}
                {% endif %}
                {{ link_to("action":url, "query":query_id, "text":action_name, "class":action_class, "target":target,  "id":id_pre ~ id, "tip":action_tip) }}
                {% if !loop.last %}
                {% set indexs =  indexs + 1 %}
                {% if (indexs>1)%}
                {{ "|" }}
                {% endif%}
                {% endif %}
                {% endfor %}
            </td>
            {% endif %}
            {# 操作区结束 #}
        </tr>
        {% endif %}
        {% endfor %}
        {# 表格数据区结束 #}
        </tbody>
    </table>

    {% if (tb_trs_data | length) <= 0 %}
    <h3 class="text-center">没有相关数据</h3>
    {% endif %}
</div>

<!--分页-->
{{ partial("partials/tp_page_pagination") }}
