<table class="form-inline table table-bordered">
    <tbody>
    <tr>
        <td>订单号：</td>
        <td>{{refund['ordercode']}}</td>
    </tr>
    <tr>
        <td>退款人：</td>
        <td>{{refund['userid']}}</td>
    </tr>
    <tr>
        <td>退款金额：</td>
        <td>{{refund['totalPrice']}}元</td>
    </tr>
    <tr>
        <td>退款原因：</td>
        <td>{{refund['mess']}}</td>
    </tr>

{%- macro create_form(form) %}
{% set form_action = form.getAction() %}
{% set default_button = form.getUserOption('default_button', true) %}

{{ form("action": form_action, "method": "post",'id':'is_pd') }}
    {% for element in form %}
    {% if is_a(element, '\Phalcon\Forms\Element\Hidden') %}
    {{ element }}
    {% else %}
    <tr>
        <td width= "120px"  nowrap>{{ element.label() }}</td>
        <td >
            {% if is_a(element, '\Phalcon\Forms\Element\Check') %}
            {{ element.render(['class' : 'js-switch']) }}
            {% elseif is_a(element, '\Phalcon\Forms\Element\TextArea') %}
            <div style="min-width:750px; width:1000px">
                {{ element.render(['class' : 'form-control err', 'rows' : '4', "style":"width:100%"]) }}
            </div>
            {% elseif is_a(element, '\App\Background\Forms\Element\CustomElement') %}
            <div style="min-width:750px; width:1000px; position: relative">
                {{ element.render() }}
            </div>
            {% else %}
            {{ element.render(['class' : 'form-control err']) }}
            {% endif %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}

    {% if form_action is defined and true == default_button %}
    <tr>
        <td colspan="2" style="padding-left: 90px;">
            <input type="hidden" name="is_access" id="is_access" value="0">
            <input name="submit" data-loading-text="正在提交..." onclick="return changec(1)" class="btn btn-default" type="submit" value="不通过">
            <input name="submit" data-loading-text="正在提交..." onclick="return changec(0)" class="btn btn-primary" type="submit"  value="通过">
        </td>
    </tr>
    {% endif %}
    </tbody>
</table>
{{ endform() }}

{%- endmacro %}

{{ create_form(form) }}
<script>
    function changec(start){
        if(start == 1){
            $('#is_access').val(1);
            if($("#mess").val() == ''){
                alert('请填写不退款说明！');
                return false;
            }
        }else{
            $('#is_access').val(0);
        }
        return true;
    }
</script>