
<!--搜索条件头部-->
{{ partial("partials/tp_page_search_ex") }}
<!--数据列表-->
<!--角色列表内容-->
{% set tb_trs = page_table["trs"] | default([]) %}
{% set tb_ths = page_table["ths"] | default([]) %}
<div>
    <table class="table table-bordered table-hover table-invoice">
        <thead>
        <tr>
            {# 表格标题区起始 #}
            <th width="50" class="text-center">ID</th>
            {% for item in tb_ths %}
            <th width="{{ item['width'] | default('') }}" class="{{ item['class'] | default('') }}" >{{ item['name'] }}</th>
            {% endfor %}
            {# 表格标题区结束 #}
        </tr>
        </thead>

        <tbody>
        {# 表格数据区起始 #}
        {# tb_trs_data表示全部列表数据 #}
        {% set tb_trs_start = tb_trs['start'] | default(1) %}
        {% set tb_trs_data = tb_trs['data'] | default(null) %}
        {% for index in 0..tb_trs_data | length %}
        {# 判断数据是否有效 #}
        {% if tb_trs_data[index] is defined %}
        {# item表示一条列表数据中数据 #}
        {% set item = tb_trs_data[index] %}
        {% set id = item['goods_id'] %}
        {% set ids = item['id'] %}
        <tr>
            {# 数据区起始 #}
            {# 编号 #}
            <td align="center">{{ids}}</td>
            {# 其他字段 #}
            {% if tb_trs['using'] is defined %}
            {# 仅使用using中指定字段 #}
            {% set fields = tb_trs['using'] %}
            {% for field in fields %}
            <td align="{{ field['align'] | default('') }}">
                {% set filed_type = field['type'] | default("text") %}
                {% if (filed_type == "image") %}
                <image class="img-thumbnail" src="{{ item[field['field']] }}" alt="图片">
                    {% else  %}
                    {{ item[field['field']] }}
                    {% endif %}
            </td>
            {% endfor %}
            {% else %}
            {# 使用全部字段 #}
            {% for item_filed in item %}
            <td>{{ item_filed }}</td>
            {% endfor %}
            {% endif %}
            {# 数据区结束 #}

            {# 操作区起始 #}
            {# ops表示所有操作 #}
            {% set ops = tb_trs['op'] | default(null) %}
            {% if ops is defined %}
            <td align="center">
                <!--{% set actions = op['actions'] | default([]) %}-->
                {% set indexs = 0 %}
                {% for action in ops %}
                {# 属性id前缀，默认前缀 MG #}
                {% set id_pre = action['id_pre'] | default("MG") %}

                {# 当产品是上架时 隐藏删除修改#}
                {% if item['is_on_sales'] == 1 %}
                    {% if id_pre == 'et_' %}
                        {% continue %}
                    {% endif %}
                    {% if id_pre == 'del_' %}
                        {% continue %}
                    {% endif %}
                {% endif %}

                {% set url = action['link'] %}
                {% set action_tip = action['tip'] | default(false) %}
                {% set target = action['target'] | default("_self") %}
                {# 默认参数 #}
                {% set query_id = ['id':id] %}
                {% set query_params = null %}
                {# 操作类型 #}
                {% if action['multiple'] is defined and action['key'] is defined %}
                {# 带有状态的操作，比如(启用/禁用) #}
                {# 获取状态值 #}

                {% set am_index = item[action['key']] %}
                {# action_attr当前状态下全部属性 #}
                {% set action_attr = action['multiple'][am_index] %}
                {# 属性class #}
                {% set action_class = action_attr['class'] | default(null) %}
                {# 操作名称 #}
                {% set action_name = action_attr['name'] | default("") %}
                {% set query_params = action['key'] ~ "=" ~ am_index %}
                {% else %}
                {# 属性class #}
                {% set action_class = action['class'] | default(null) %}
                {# 操作名称 #}
                {% set action_name = action['name'] | default("") %}
                {% endif %}

                {# a 标签使用post方式提交请求, 务必引用qst_table.js #}
                {% if (action['method'] | default("get")) == "post" %}
                {% set action_class = action_class ~ " mg_post" %}
                {% endif %}
                {% if query_params is defined %}
                {% set url = url ~ "?" ~ query_params %}
                {% endif %}
                {{ link_to("action":url, "query":query_id, "text":action_name, "class":action_class, "target":target,  "id":id_pre ~ id, "tip":action_tip) }}
                {% if !loop.last %}
                {% set indexs =  indexs + 1 %}
                    {% if item['is_on_sales'] == 1 %}
                        {% if indexs == 2  %}
                            {% continue %}
                        {% endif %}
                    {% endif %}
                    {{ "|" }}
                {% endif %}
                {% endfor %}
            </td>
            {% endif %}
            {# 操作区结束 #}
        </tr>
        {% endif %}
        {% endfor %}
        {# 表格数据区结束 #}
        </tbody>
    </table>

    {% if (tb_trs_data | length) <= 0 %}
    <h3 class="text-center">没有相关数据</h3>
    {% endif %}
</div>

<!--分页-->
{{ partial("partials/tp_page_pagination") }}
<script>
var aa = GetRequest();
var pdata = {{pData}};
var cdata = {{cData}};
var currCat_id = {{cat_ide}};

$('.table').find('a').each(function (val, key) {
    var urls = $(this).attr('href')+'&'+aa;
    $(this).attr('href',urls);
})
function GetRequest() {
    var url = location.search; //获取url中"?"符后的字串
    var str = '';
    if (url.indexOf("?") != -1) {
        str = url.substr(1);
    }
    return str;
}
$(function () {
    $('#cat_id').change(function () {
        var cat_id = $(this).val();
        if(cat_id == 'goods_name'){
            var options = '<option value="">请选择</optiop>';
            $.map(pdata,function(v,k){
                options += '<option value="'+ k+'">'+ v+'</option>';
            })
            $('#cat_ide').empty().append(options);
        }
        if(cat_id == 'goods_id'){
            changeOption();
        }
    })
})

/*if(pcate_id != 0){
    $('#cat_id').val(pcate_id);
}*/
/*if(cate_id != 0){
    changeOption(pcate_id);
    $('#cat_ide').val(cate_id);
}*/
//已经选择过分类以后要出来二级分类
var cat_id = $('#cat_id').val();
if(cat_id == 'goods_name'){
    var options = '<option value="">请选择</optiop>';
    $.map(pdata,function(v,k){
        options += '<option value="'+ k+'">'+ v+'</option>';
    })
    $('#cat_ide').empty().append(options);
}
if(cat_id == 'goods_id'){
    changeOption();
}
//二级分类填充
function changeOption(){
    var options = '<option value="">请选择</option>';
    $.map(cdata, function (val,key) {
        $.map(val,function(v,k){
            options += '<option value="'+ v.id+'">'+ v.title+'</option>';
        })
    });
    $('#cat_ide').empty().append(options);
}
if(currCat_id == 0){
    $('#cat_ide').val('');
}else{
    $('#cat_ide').val(currCat_id);
}

</script>