<?php
/**
 * Created by PhpStorm.
 * User: miaogang
 * Date: 2016/8/23
 * Time: 12:36
 */

namespace App\Background\Controllers;

use App\Models\Message;
use Plugin\Core\QSTBaseException;
use Phalcon\Mvc\Dispatcher;
use Plugin\Core\QSTBaseController;

class BaseController extends QSTBaseController
{
    const DEFAULT_PAGE_ROW = 20;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->view->nav_menu = array("name" => "后台管理中心", "link" => "admin");
        $this->view->ht_user_name = $this->login->getName();
        //统计待收消息
        $userid = $this->session->get('auth-identity')['id'];//获取用户id
        $roleid = $this->session->get('auth-identity')['profile'];
        $this->view->messageNum = Message::count('recid = '.$userid.' and statue = 0');
        $messagess = '/sunny/admin/message/search';
        if($roleid > 1){
            $messagess = '/sunny/admin/message/getMessage';
        }
        $this->view->roleid = $roleid;
        $this->view->messageLink = $messagess;
    }

    /**
     * @param Dispatcher $dispatcher
     * @return bool
     * @throws \Exception
     */
    public function beforeExecuteRoute(Dispatcher $dispatcher)
    {
        // Get the current identity
        $identity = $this->login->getIdentity();
        // If there is no identity available the user is redirected to index/index
        if (false == $identity || !is_array($identity)) {
            $this->session->set("redirect_from", $this->request->getURI());
            $dispatcher->forward(array(
                'controller' => 'session',
                'action' => 'index'
            ));
            return false;
        }
        $controllerName = $dispatcher->getControllerName();
        //$access = $dispatcher->getActionName() . "!" . $this->request->getMethod();

        /*if (!$this->rbac->isAllowed($identity['profile'], $controllerName, $access)) {
            throw new QSTBaseException('You don\'t have access to this module: ' . $controllerName . ':' . $access, 403);
        }*/
    }
}