<?php
/**
 * Created by PhpStorm.
 * User: dodo
 * Date: 2016/8/1
 * Time: 21:18
 */

namespace App\Background\Controllers;

use App\Background\Forms\UserForm;
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;
use Phalcon\Mvc\View;

/**
 * Display the default index page.
 */
class ComponentsController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        /*$menu = $this->menu;
        $menu['components']['active'] = true;
        $menu['components']['sub_menu']['groups']['link_action'] = "";
        $menu['components']['sub_menu']['groups']['active'] = true;
        $this->view->menu_root = $menu;
        $this->view->nav_menu = array_merge(array($this->view->nav_menu, array("name" => "客户管理列表", "link" => "admin")));
        $this->assets->addCss('public/static/background/css/common.css');
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shCore.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushPhp.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushXml.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushJScript.js");
        $this->addLibCss("libs/js3party/syntaxhighlighter_3.0.83/styles/shCore.css");
        $this->addLibCss("libs/js3party/syntaxhighlighter_3.0.83/styles/shThemeDefault.css");*/
    }

    private function makeMenu($action)
    {
        $menu = $this->menu;
        $menu['components']['active'] = true;
        $menu['components']['sub_menu'][$action]['link_action'] = "";
        $menu['components']['sub_menu'][$action]['active'] = true;
        $this->view->menu_root = $menu;
        $this->view->nav_menu = array_merge(array($this->view->nav_menu, array("name" => "客户管理列表", "link" => "admin")));
        $this->assets->addCss('public/static/background/css/common.css');
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shCore.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushPhp.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushXml.js");
        $this->addLibJs("libs/js3party/syntaxhighlighter_3.0.83/scripts/shBrushJScript.js");
        $this->addLibCss("libs/js3party/syntaxhighlighter_3.0.83/styles/shCore.css");
        $this->addLibCss("libs/js3party/syntaxhighlighter_3.0.83/styles/shThemeDefault.css");
    }

    public function indexAction()
    {
        $this->response->redirect("admin/index/search");
    }

    public function FormAction()
    {
        if($this->request->isGet()){
            $this->addLibJs("libs/jsapi/form-mutex-operations.js");
            $this->makeMenu('form');
            $this->view->setVar("ts", array(
                'label' => "",
                "key" => "test",
                "candidates"=>array(
                    array("key"=>"1", "name"=>"活动策划与执行"),
                    array("key"=>"2", "name"=>"海外项目经验"),
                    array("key"=>"3", "name"=>"调研 用户洞察、行业调研、分析"),
                    array("key"=>"4", "name"=>"媒介购买与管理"),
                    array("key"=>"51", "name"=>"旅游 "),
                    array("key"=>"6", "name"=>"公共关系"),
                    array("key"=>"7", "name"=>"活动策划与执行"),
                    array("key"=>"8", "name"=>"海外项目经验"),
                    array("key"=>"9", "name"=>"调研 用户洞察、行业调研、分析"),
                    array("key"=>"10", "name"=>"媒介购买与管理"),
                    array("key"=>"11", "name"=>"旅游 "),
                    array("key"=>"12", "name"=>"公共关系")),
                "chosen"=>array("chosenId"=>array("1", "3", "10")),
                "maxChosen"=>7,
                'selfSubmit' => true,
                'buttonDisplay' => "测试1"
            ));
            $this->view->setVar("mutexOps", array(
                array("name" => "审核通过", "status" => "1", "type" => "submit"),
                array("name" => "审核未通过", "status" => "2", "type" => "pop", 'title'=>'审核不通过原因：', 'placeholder'=>"不超过100个字符"),
                array("name" => "延期处理", "status" => "3", "type" => "pop", 'title'=>'延期原因：', 'placeholder'=>"不超过100个字符"),
                array("name" => "返回", "status" => "1", "type" => "back"),
            ));
            $this->view->setVar("dataSelector", array(
                'selector'=>array(//选择器组件配置
                    'dataUrl'=>"/qstfw/webprj/admin/index/tareas", //获取分级数据的url
                    "levels"=>array(//分级数据选择按钮配置
                        array('type'=>"city", "prompt"=>"请选择城市"),//数据类型和无数据时默认显示的内容
                        array('type'=>"county", "prompt"=>"请选择区县"),
                        array('type'=>"town", "prompt"=>"请选择社区"),
                    )
                ),
                'trigger'=>array(//触发选择弹框及隐藏提交表单的配置
                    'label'=>'',//前置说明标签
                    'defaultDisplay'=>'请选择地址',//无数据时显示的值
                    'idItem'=>array(//隐藏提交表单，分级数据id，不同级别之间以"-"分割
                        'key' =>'addrid',//提交表单的key
                        'value'=>'0-0-0' //当前数据，如需回显已保存数据，则需要该字段
                    ),
                    'nameItem'=>array(//隐藏提交表单，分级数据名称，不同级别之间以"-"分割
                        'key'=>'addr', //提交表单的key
                        'value'=>'北京-朝阳-望京' //当前数据，如需回显已保存数据，则需要该字段
                    )
                )
            ));

        }else if($this->request->isPost()){
            $str = $this->request->getPost('test');
            $this->log("000000000000000");
            $out = json_decode($str, true);
            if(false == $out){
                $this->log("1111111111111");
            }else{
                $this->log("2222222222222222");
                $this->log("AAAAA--".$out['chosen'][0]);
            }
            $this->log(json_encode($this->request->getPost()));
            return $this->response->redirect("admin/components/form");
        }
    }
    public function GroupsAction()
    {
        if($this->request->isGet()){
            $this->makeMenu('groups');
            $this->view->setVar("ctest", array(
                array('type' => "KeySet", 'data' => array('key'=>"服务过的品牌", "value"=>"宝洁 、京东")),
                array('data' => array('key'=>"能力经验", "value"=>"海外项目经验 ；服务4A公司")),
                array('data' => array('key'=>"服务知名公司", "value"=>"XXXXXXXXXXX")),
                array('data' => array('key'=>"获奖经历", "value"=>"XXXXXXXXXXX")),
                array('data' => array('key'=>"所获奖项", "value"=>"*****广告最具创意奖")),
                array('data' => array('key'=>"擅长领域", "value"=>"医疗、快消品")),
                array('data' => array('key'=>"擅长类型", "value"=>"市场营销顾问；媒介购买与管理")),
                array('type'=> 'KeyTable',
                    'data' => array(
                        'key' => "数据表",
                        'data' => array(
                            "headers" => array( //表头
                                array('name' => "承接项目内容", //表头名称
                                    "asTh" => 1, //该列数据是否使用
                                    'key' => "fir" //对应数据key
                                ),
                                array('name' => "预算报价", 'key' => "sec"),),
                            "data" => array( //表数据
                                array('fir' => "海报", 'sec' => "￥2,000,00元/幅", 'thr' => "third--------"),
                                array('fir' => "海报2", 'sec' => "￥2,000,00元/幅", 'thr' => "third--------"),
                                array('fir' => "海报3", 'sec' => "￥2,000,00元/幅", 'thr' => "third--------"),
                                array('fir' => "海报4", 'sec' => "￥2,000,00元/幅", 'thr' => "third--------"),
                            ))),
                )));
            $this->view->setVar("ctest_text", array(
                array('data' => array(
                    "title" => "北京邮电大学",
                    "subtitleA" => "数字媒体技术 I 学士",
                    "subtitleB" => "2015.4-至今",
                    "content" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget."
                )),
                array('data' => array(
                    "title" => "圣乔治大学",
                    "subtitleA" => "十字圣光",
                    "subtitleB" => "前225-2015.4",
                    "content" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget."
                ))
            ));

            $this->view->setVar("ctest_thumbs", array(
                array(
                    'image'=>array('src' => 'http://img05.tooopen.com/images/20150202/sy_80219211654.jpg', 'link'=>"#", "alt"=>"sljf"),//图片
                    "title"=>"一切为了开心嘛",//标题
                    "content"=>"",//说明内容
                    "labelLinks"=>array(//标签组
                        array("link" => "#", "name" => "营销策略"),
                        array("link" => "#", "name" => "需求详情"),
                        array("link" => "#", "name" => "候选人名单"),
                        array("link" => "#", "name" => "法撒旦就"),
                    )
                ),
                array(
                    'image'=>array('src' => 'http://img04.tooopen.com/images/20130530/tooopen_19112658.jpg', 'link'=>"#", "alt"=>"sljf"),//图片
                    "title"=>"一切为了开心嘛",//标题
                    "content"=>"",//说明内容
                    "labelLinks"=>array(//标签组
                        array("link" => "#", "name" => "营销策略"),
                        array("link" => "#", "name" => "需求详情"),
                        array("link" => "#", "name" => "候选人名单"),
                        array("link" => "#", "name" => "法撒旦就"),
                    )
                ),
                array(
                    'image'=>array('src' => 'http://img04.tooopen.com/images/20130701/tooopen_10055061.jpg', 'link'=>"#", "alt"=>"sljf"),//图片
                    "title"=>"一切为了开心嘛",//标题
                    "content"=>"",//说明内容
                    "labelLinks"=>array(//标签组
                        array("link" => "#", "name" => "营销策略"),
                        array("link" => "#", "name" => "需求详情"),
                        array("link" => "#", "name" => "候选人名单"),
                        array("link" => "#", "name" => "法撒旦就"),
                    )
                ),
                array(
                    'image'=>array('src' => 'http://img04.tooopen.com/images/20130701/tooopen_20083555.jpg', 'link'=>"#", "alt"=>"sljf"),//图片
                    "title"=>"一切为了开心嘛",//标题
                    "content"=>"",//说明内容
                    "labelLinks"=>array(//标签组
                        array("link" => "#", "name" => "营销策略"),
                        array("link" => "#", "name" => "需求详情"),
                        array("link" => "#", "name" => "候选人名单"),
                        array("link" => "#", "name" => "法撒旦就"),
                    )
                ),
            ));
        }else{
            return $this->response->redirect("admin/components/groups");
        }
    }
    public function TableAction()
    {
        if($this->request->isGet()){
            $this->addLibJs("libs/jsapi/check_table.js");
            $this->makeMenu('table');
            $tb_ths = [];
            $tb_ths[] = array("name" => "头像", "width" => "80");
            $tb_ths[] = array("name" => "手机", "width" => "100");
            $tb_ths[] = array("name" => "公司",);
            $tb_ths[] = array("name" => "联系人", "width" => "100");
            $tb_ths[] = array("name" => "城市", "width" => "100");
            $tb_ths[] = array("name" => "销售代表", "width" => "100");
            $tb_ths[] = array("name" => "注册时间", "width" => "180");
            $using = array(
                ["field" => 'head', "type" => "image"],
                ["field" => "tel"],
                ["field" => "company_name"],
                ["field" => 'vname'],
                ["field" => 'livecity'],
                ["field" => 'sales'],
                ["field" => 'time']
            );
            $tableStatus = array('active', "success", "warning", "danger", "info", "");
            $tb_trs = array(
                "data" => array(
                    array(
                        "tableStatus"=>$tableStatus[0],
                        'id' => 10,
                        'head' => "http://img05.tooopen.com/images/20150202/sy_80219211654.jpg",
                        "company_name" => "北京骑士团科技有限公司",
                        'tel' => "13888880000",
                        'vname' => "苗刚",
                        "zhtel" => "010-10901211",
                        "livecity" => "北京",
                        "sales" => "10001",
                        "time" => "2016-11-11 12:11:11",
                        "operation" => "adffff"
                    ),
                    array(
                        "checked" => true,
                        "disabled" => true,
                        "tableStatus"=>$tableStatus[1],
                        'id' => 9,
                        'head' => "http://img05.tooopen.com/images/20150202/sy_80219211654.jpg",
                        "company_name" => "北京骑士团科技有限公司",
                        'tel' => "13888880000",
                        'vname' => "苗刚",
                        "zhtel" => "010-10901211",
                        "livecity" => "北京",
                        "sales" => "10001",
                        "time" => "2016-11-11 12:11:11",
                        "operation" => "adffff"
                    ),
                    array(
                        "tableStatus"=>$tableStatus[2],
                        'id' => 8,
                        'head' => "http://img05.tooopen.com/images/20150202/sy_80219211654.jpg",
                        "company_name" => "北京骑士团科技有限公司",
                        'tel' => "13888880000",
                        'vname' => "苗刚",
                        "zhtel" => "010-10901211",
                        "livecity" => "北京",
                        "sales" => "10001",
                        "time" => "2016-11-11 12:11:11",
                        "operation" => "adffff"
                    ),
                    array(
                        "tableStatus"=>$tableStatus[3],
                        'id' => 7,
                        'head' => "http://img05.tooopen.com/images/20150202/sy_80219211654.jpg",
                        "company_name" => "北京骑士团科技有限公司",
                        'tel' => "13888880000",
                        'vname' => "苗刚",
                        "zhtel" => "010-10901211",
                        "livecity" => "北京",
                        "sales" => "10001",
                        "time" => "2016-11-11 12:11:11",
                        "operation" => "adffff"
                    ),
                    array(
                        "tableStatus"=>$tableStatus[4],
                        'id' => 6,
                        'head' => "http://img05.tooopen.com/images/20150202/sy_80219211654.jpg",
                        "company_name" => "北京骑士团科技有限公司",
                        'tel' => "13888880000",
                        'vname' => "苗刚",
                        "zhtel" => "010-10901211",
                        "livecity" => "北京",
                        "sales" => "10001",
                        "time" => "2016-11-11 12:11:11",
                        "operation" => "adffff"
                    )
                ),
                "using" => $using
            );
            $this->view->setVar("trs", $tb_trs);
            $this->view->setVar("ths", $tb_ths);
            $this->view->setVar("batchOperations", array(
                array('name'=>'提交', //操作按钮显示名称
                    'link'=>"admin/components/table" //操作请求（POST）url
                ),
                array('name'=>'发送', 'link'=>"admin/components/table"),
            ));
            $queryArray['page'] = "";
            $this->view->setVar("pager", array(
                'cur'=>1, //当前页码
                'total'=>10, //总页数
                'url'=>$this->url->get('admin/components/table?' . http_build_query($queryArray)),//页码跳转url
                'data_total'=>100 //数据总条数
            ));
        }else if($this->request->isPost()){
            $this->log($this->request->getRawBody());
            return $this->response->redirect("admin/components/table");
        }
    }
}
