{{ partial("partials/tp_page_form") }}
<script>
    $('.btn-success').click(function () {
        $(this).removeClass('mutex-btn-submit');

        var opassword = $('#opassword').val();
        if(opassword == ''){
            alert('请输入密码！');
            $('#opassword').focus();
            return false;
        }

        var password = $('#password').val();
        if(password == ''){
            alert('请输入密码！');
            $('#password').focus();
            return false;
        }

        var pw_confirm = $('#pw_confirm').val();
        if(pw_confirm == ''){
            alert('确认密码不能为空！');
            $('#pw_confirm').focus();
            return false;
        }
        if(pw_confirm != password){
            alert('两次输入的密码不等！');
            $('#pw_confirm').focus();
            return false;
        }
        $("form")[0].submit();
    });
</script>